 Network rinha_backend_2024_q1  Creating
 Network rinha_backend_2024_q1  Created
 Container rodrigocaldeira-db-1  Creating
 Container rodrigocaldeira-db-1  Created
 Container rodrigocaldeira-api01-1  Creating
 Container rodrigocaldeira-api01-1  Created
 Container rodrigocaldeira-api02-1  Creating
 Container rodrigocaldeira-api02-1  Created
 Container rodrigocaldeira-nginx-1  Creating
 Container rodrigocaldeira-nginx-1  Created
Attaching to api01-1, api02-1, db-1, nginx-1
db-1     | The files belonging to this database system will be owned by user "postgres".
db-1     | This user must also own the server process.
db-1     | 
db-1     | The database cluster will be initialized with locale "en_US.utf8".
db-1     | The default database encoding has accordingly been set to "UTF8".
db-1     | The default text search configuration will be set to "english".
db-1     | 
db-1     | Data page checksums are disabled.
db-1     | 
db-1     | fixing permissions on existing directory /var/lib/postgresql/data ... ok
db-1     | creating subdirectories ... ok
db-1     | selecting dynamic shared memory implementation ... posix
db-1     | selecting default max_connections ... 100
db-1     | selecting default shared_buffers ... 128MB
db-1     | selecting default time zone ... Etc/UTC
db-1     | creating configuration files ... ok
db-1     | running bootstrap script ... ok
db-1     | performing post-bootstrap initialization ... ok
db-1     | syncing data to disk ... ok
db-1     | 
db-1     | 
db-1     | Success. You can now start the database server using:
db-1     | 
db-1     |     pg_ctl -D /var/lib/postgresql/data -l logfile start
db-1     | 
db-1     | initdb: warning: enabling "trust" authentication for local connections
db-1     | initdb: hint: You can change this by editing pg_hba.conf or using the option -A, or --auth-local and --auth-host, the next time you run initdb.
db-1     | waiting for server to start....2024-02-17 16:33:04.260 UTC [48] LOG:  starting PostgreSQL 16.2 (Debian 16.2-1.pgdg120+2) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
db-1     | 2024-02-17 16:33:04.262 UTC [48] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db-1     | 2024-02-17 16:33:04.270 UTC [51] LOG:  database system was shut down at 2024-02-17 16:33:02 UTC
db-1     | 2024-02-17 16:33:04.283 UTC [48] LOG:  database system is ready to accept connections
db-1     |  done
db-1     | server started
db-1     | CREATE DATABASE
db-1     | 
db-1     | 
db-1     | /usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*
db-1     | 
db-1     | waiting for server to shut down...2024-02-17 16:33:04.447 UTC [48] LOG:  received fast shutdown request
db-1     | .2024-02-17 16:33:04.450 UTC [48] LOG:  aborting any active transactions
db-1     | 2024-02-17 16:33:04.452 UTC [48] LOG:  background worker "logical replication launcher" (PID 54) exited with exit code 1
db-1     | 2024-02-17 16:33:04.452 UTC [49] LOG:  shutting down
db-1     | 2024-02-17 16:33:04.455 UTC [49] LOG:  checkpoint starting: shutdown immediate
db-1     | 2024-02-17 16:33:04.921 UTC [49] LOG:  checkpoint complete: wrote 923 buffers (5.6%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.369 s, sync=0.087 s, total=0.470 s; sync files=301, longest=0.061 s, average=0.001 s; distance=4257 kB, estimate=4257 kB; lsn=0/19130B0, redo lsn=0/19130B0
db-1     | 2024-02-17 16:33:04.926 UTC [48] LOG:  database system is shut down
db-1     |  done
db-1     | server stopped
db-1     | 
db-1     | PostgreSQL init process complete; ready for start up.
db-1     | 
db-1     | 2024-02-17 16:33:04.970 UTC [1] LOG:  starting PostgreSQL 16.2 (Debian 16.2-1.pgdg120+2) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
db-1     | 2024-02-17 16:33:04.970 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db-1     | 2024-02-17 16:33:04.970 UTC [1] LOG:  listening on IPv6 address "::", port 5432
db-1     | 2024-02-17 16:33:04.975 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db-1     | 2024-02-17 16:33:04.981 UTC [64] LOG:  database system was shut down at 2024-02-17 16:33:04 UTC
db-1     | 2024-02-17 16:33:04.988 UTC [1] LOG:  database system is ready to accept connections
nginx-1  | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
nginx-1  | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
nginx-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
nginx-1  | 10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
nginx-1  | 10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
nginx-1  | /docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh
nginx-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
nginx-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
nginx-1  | /docker-entrypoint.sh: Configuration complete; ready for start up
nginx-1  | 2024/02/17 16:33:07 [error] 30#30: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.128.3:4000/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/17 16:33:07 [error] 30#30: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.128.4:4001/clientes/1/extrato", host: "localhost:9999"
api01-1  | 16:33:09.521 [info] == Running 20240205222402 RinhaBackend.Repo.Migrations.CreateClientes.change/0 forward
api01-1  | 16:33:09.523 [info] create table clientes
api01-1  | 16:33:09.535 [info] create check constraint saldo_maior_que_o_limite on table clientes
api01-1  | 16:33:09.536 [info] == Migrated 20240205222402 in 0.0s
nginx-1  | 2024/02/17 16:33:09 [error] 30#30: *4 no live upstreams while connecting to upstream, client: 192.168.128.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
api01-1  | 16:33:09.728 [info] == Running 20240206075612 RinhaBackend.Repo.Migrations.SeedsClientesTable.up/0 forward
api01-1  | 16:33:09.730 [info] == Migrated 20240206075612 in 0.0s
nginx-1  | 2024/02/17 16:33:11 [error] 30#30: *5 no live upstreams while connecting to upstream, client: 192.168.128.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/17 16:33:13 [error] 30#30: *6 no live upstreams while connecting to upstream, client: 192.168.128.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/17 16:33:15 [error] 30#30: *7 no live upstreams while connecting to upstream, client: 192.168.128.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
api02-1 exited with code 137
api01-1 exited with code 137
nginx-1  | 2024/02/17 16:33:17 [error] 30#30: *8 no live upstreams while connecting to upstream, client: 192.168.128.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/17 16:34:19 [error] 30#30: *9 upstream timed out (110: Connection timed out) while connecting to upstream, client: 192.168.128.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.128.4:4001/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/17 16:34:38 [error] 30#30: *9 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.128.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.128.3:4000/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/17 16:34:43 [error] 30#30: *12 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.128.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.128.4:4001/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/17 16:34:43 [error] 30#30: *12 no live upstreams while connecting to upstream, client: 192.168.128.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/17 16:34:45 [error] 30#30: *14 no live upstreams while connecting to upstream, client: 192.168.128.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/17 16:34:47 [error] 30#30: *15 no live upstreams while connecting to upstream, client: 192.168.128.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/17 16:34:52 [error] 30#30: *16 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.128.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.128.3:4000/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/17 16:34:52 [error] 30#30: *16 no live upstreams while connecting to upstream, client: 192.168.128.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/17 16:34:57 [error] 30#30: *18 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.128.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.128.4:4001/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/17 16:34:57 [error] 30#30: *18 no live upstreams while connecting to upstream, client: 192.168.128.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/17 16:34:59 [error] 30#30: *20 no live upstreams while connecting to upstream, client: 192.168.128.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/17 16:35:01 [error] 30#30: *21 no live upstreams while connecting to upstream, client: 192.168.128.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/17 16:35:06 [error] 30#30: *22 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.128.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.128.3:4000/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/17 16:35:06 [error] 30#30: *22 no live upstreams while connecting to upstream, client: 192.168.128.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/17 16:35:11 [error] 30#30: *24 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.128.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.128.4:4001/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/17 16:35:11 [error] 30#30: *24 no live upstreams while connecting to upstream, client: 192.168.128.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/17 16:35:13 [error] 30#30: *26 no live upstreams while connecting to upstream, client: 192.168.128.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/17 16:35:15 [error] 30#30: *27 no live upstreams while connecting to upstream, client: 192.168.128.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/17 16:35:20 [error] 30#30: *28 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.128.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.128.3:4000/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/17 16:35:20 [error] 30#30: *28 no live upstreams while connecting to upstream, client: 192.168.128.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1 exited with code 0
nginx-1 exited with code 0
db-1     | 2024-02-17 16:35:23.690 UTC [1] LOG:  received fast shutdown request
db-1     | 2024-02-17 16:35:23.693 UTC [1] LOG:  aborting any active transactions
db-1     | 2024-02-17 16:35:23.695 UTC [1] LOG:  background worker "logical replication launcher" (PID 67) exited with exit code 1
db-1     | 2024-02-17 16:35:23.696 UTC [62] LOG:  shutting down
db-1     | 2024-02-17 16:35:23.698 UTC [62] LOG:  checkpoint starting: shutdown immediate
db-1     | 2024-02-17 16:35:23.797 UTC [62] LOG:  checkpoint complete: wrote 100 buffers (0.6%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.008 s, sync=0.080 s, total=0.101 s; sync files=51, longest=0.073 s, average=0.002 s; distance=459 kB, estimate=459 kB; lsn=0/1985D40, redo lsn=0/1985D40
db-1     | 2024-02-17 16:35:23.800 UTC [1] LOG:  database system is shut down
db-1 exited with code 0
