 Network rinha-nginx-2024q1  Creating
 Network rinha-nginx-2024q1  Created
 Container lucianovilela-db-1  Creating
 Container lucianovilela-db-1  Created
 Container lucianovilela-api01-1  Creating
 Container lucianovilela-api02-1  Creating
 Container lucianovilela-api01-1  Created
 Container lucianovilela-api02-1  Created
 Container lucianovilela-nginx-1  Creating
 Container lucianovilela-nginx-1  Created
Attaching to api01-1, api02-1, db-1, nginx-1
db-1     | The files belonging to this database system will be owned by user "postgres".
db-1     | This user must also own the server process.
db-1     | 
db-1     | The database cluster will be initialized with locale "en_US.utf8".
db-1     | The default database encoding has accordingly been set to "UTF8".
db-1     | The default text search configuration will be set to "english".
db-1     | 
db-1     | Data page checksums are disabled.
db-1     | 
db-1     | fixing permissions on existing directory /var/lib/postgresql/data ... ok
db-1     | creating subdirectories ... ok
db-1     | selecting dynamic shared memory implementation ... posix
db-1     | selecting default max_connections ... 100
db-1     | selecting default shared_buffers ... 128MB
db-1     | selecting default time zone ... Etc/UTC
db-1     | creating configuration files ... ok
db-1     | running bootstrap script ... ok
api01-1  | Servidor rodando na porta 9000
api02-1  | Servidor rodando na porta 9001
nginx-1  | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
nginx-1  | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
nginx-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
nginx-1  | 10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
nginx-1  | 10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
nginx-1  | /docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh
nginx-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
nginx-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
nginx-1  | /docker-entrypoint.sh: Configuration complete; ready for start up
db-1     | performing post-bootstrap initialization ... ok
db-1     | syncing data to disk ... ok
db-1     | 
db-1     | 
db-1     | Success. You can now start the database server using:
db-1     | 
db-1     |     pg_ctl -D /var/lib/postgresql/data -l logfile start
db-1     | 
db-1     | initdb: warning: enabling "trust" authentication for local connections
db-1     | initdb: hint: You can change this by editing pg_hba.conf or using the option -A, or --auth-local and --auth-host, the next time you run initdb.
db-1     | waiting for server to start....2024-02-13 23:48:55.539 UTC [48] LOG:  starting PostgreSQL 16.2 (Debian 16.2-1.pgdg120+2) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
db-1     | 2024-02-13 23:48:55.546 UTC [48] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db-1     | 2024-02-13 23:48:55.593 UTC [51] LOG:  database system was shut down at 2024-02-13 23:48:54 UTC
db-1     | 2024-02-13 23:48:55.611 UTC [48] LOG:  database system is ready to accept connections
db-1     |  done
db-1     | server started
api01-1  | /app/node_modules/pg-pool/index.js:45
api01-1  |     Error.captureStackTrace(err);
api01-1  |           ^
api01-1  | 
api01-1  | Error: connect ECONNREFUSED 192.168.96.2:5432
api01-1  |     at /app/node_modules/pg-pool/index.js:45:11
api01-1  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
api01-1  |     at async /app/index.js:32:25 {
api01-1  |   errno: -111,
api01-1  |   code: 'ECONNREFUSED',
api01-1  |   syscall: 'connect',
api01-1  |   address: '192.168.96.2',
api01-1  |   port: 5432
api01-1  | }
api01-1  | 
api01-1  | Node.js v20.11.0
nginx-1  | 2024/02/13 23:48:55 [error] 29#29: *1 upstream prematurely closed connection while reading response header from upstream, client: 192.168.96.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.96.3:9000/clientes/1/extrato", host: "localhost:9999"
api02-1  | /app/node_modules/pg-pool/index.js:45
api02-1  |     Error.captureStackTrace(err);
api02-1  |           ^
api02-1  | 
api02-1  | Error: connect ECONNREFUSED 192.168.96.2:5432
api02-1  |     at /app/node_modules/pg-pool/index.js:45:11
api02-1  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
api02-1  |     at async /app/index.js:32:25 {
api02-1  |   errno: -111,
api02-1  |   code: 'ECONNREFUSED',
api02-1  |   syscall: 'connect',
api02-1  |   address: '192.168.96.2',
api02-1  |   port: 5432
api02-1  | }
api02-1  | 
api02-1  | Node.js v20.11.0
nginx-1  | 2024/02/13 23:48:55 [error] 29#29: *1 upstream prematurely closed connection while reading response header from upstream, client: 192.168.96.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.96.4:9001/clientes/1/extrato", host: "localhost:9999"
db-1     | CREATE DATABASE
db-1     | 
db-1     | 
db-1     | /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/init.sql
db-1     | CREATE TABLE
db-1     | CREATE TABLE
db-1     | CREATE TABLE
db-1     | DO
db-1     | 
db-1     | 
db-1     | 2024-02-13 23:48:56.543 UTC [48] LOG:  received fast shutdown request
db-1     | waiting for server to shut down....2024-02-13 23:48:56.585 UTC [48] LOG:  aborting any active transactions
db-1     | 2024-02-13 23:48:56.588 UTC [48] LOG:  background worker "logical replication launcher" (PID 54) exited with exit code 1
db-1     | 2024-02-13 23:48:56.589 UTC [49] LOG:  shutting down
db-1     | 2024-02-13 23:48:56.693 UTC [49] LOG:  checkpoint starting: shutdown immediate
api02-1 exited with code 1
api01-1 exited with code 1
db-1     | 2024-02-13 23:48:57.054 UTC [49] LOG:  checkpoint complete: wrote 944 buffers (5.8%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.249 s, sync=0.026 s, total=0.466 s; sync files=310, longest=0.005 s, average=0.001 s; distance=4313 kB, estimate=4313 kB; lsn=0/19211D8, redo lsn=0/19211D8
db-1     | 2024-02-13 23:48:57.062 UTC [48] LOG:  database system is shut down
db-1     |  done
db-1     | server stopped
db-1     | 
db-1     | PostgreSQL init process complete; ready for start up.
db-1     | 
db-1     | 2024-02-13 23:48:57.236 UTC [1] LOG:  starting PostgreSQL 16.2 (Debian 16.2-1.pgdg120+2) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
db-1     | 2024-02-13 23:48:57.236 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db-1     | 2024-02-13 23:48:57.236 UTC [1] LOG:  listening on IPv6 address "::", port 5432
db-1     | 2024-02-13 23:48:57.288 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db-1     | 2024-02-13 23:48:57.345 UTC [66] LOG:  database system was shut down at 2024-02-13 23:48:57 UTC
db-1     | 2024-02-13 23:48:57.360 UTC [1] LOG:  database system is ready to accept connections
nginx-1  | 2024/02/13 23:49:58 [error] 30#30: *4 upstream timed out (110: Connection timed out) while connecting to upstream, client: 192.168.96.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.96.3:9000/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/13 23:50:16 [error] 30#30: *4 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.96.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.96.4:9001/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/13 23:50:37 [error] 32#32: *7 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.96.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.96.3:9000/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/13 23:50:40 [error] 32#32: *7 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.96.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.96.4:9001/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/13 23:50:45 [error] 31#31: *10 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.96.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.96.3:9000/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/13 23:50:48 [error] 31#31: *10 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.96.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.96.4:9001/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/13 23:50:51 [error] 29#29: *13 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.96.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.96.4:9001/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/13 23:50:54 [error] 29#29: *13 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.96.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.96.3:9000/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/13 23:50:56 [error] 29#29: *16 no live upstreams while connecting to upstream, client: 192.168.96.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/13 23:50:58 [error] 29#29: *17 no live upstreams while connecting to upstream, client: 192.168.96.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/13 23:51:00 [error] 29#29: *18 no live upstreams while connecting to upstream, client: 192.168.96.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/13 23:51:05 [error] 29#29: *19 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.96.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.96.4:9001/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/13 23:51:08 [error] 29#29: *19 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.96.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.96.3:9000/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/13 23:51:10 [error] 29#29: *22 no live upstreams while connecting to upstream, client: 192.168.96.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/13 23:51:12 [error] 29#29: *23 no live upstreams while connecting to upstream, client: 192.168.96.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/13 23:51:14 [error] 29#29: *24 no live upstreams while connecting to upstream, client: 192.168.96.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/13 23:51:19 [error] 29#29: *25 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.96.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.96.4:9001/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/13 23:51:22 [error] 29#29: *25 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.96.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.96.3:9000/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/13 23:51:24 [error] 29#29: *28 no live upstreams while connecting to upstream, client: 192.168.96.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/13 23:51:26 [error] 29#29: *29 no live upstreams while connecting to upstream, client: 192.168.96.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/13 23:51:28 [error] 29#29: *30 no live upstreams while connecting to upstream, client: 192.168.96.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/13 23:51:33 [error] 29#29: *31 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.96.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.96.4:9001/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/13 23:51:36 [error] 29#29: *31 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.96.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.96.3:9000/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/13 23:51:38 [error] 29#29: *34 no live upstreams while connecting to upstream, client: 192.168.96.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/13 23:51:40 [error] 29#29: *35 no live upstreams while connecting to upstream, client: 192.168.96.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/13 23:51:42 [error] 29#29: *36 no live upstreams while connecting to upstream, client: 192.168.96.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1 exited with code 0
nginx-1 exited with code 0
db-1     | 2024-02-13 23:51:45.581 UTC [1] LOG:  received fast shutdown request
db-1     | 2024-02-13 23:51:45.583 UTC [1] LOG:  aborting any active transactions
db-1     | 2024-02-13 23:51:45.586 UTC [1] LOG:  background worker "logical replication launcher" (PID 69) exited with exit code 1
db-1     | 2024-02-13 23:51:45.588 UTC [64] LOG:  shutting down
db-1     | 2024-02-13 23:51:45.590 UTC [64] LOG:  checkpoint starting: shutdown immediate
db-1     | 2024-02-13 23:51:45.611 UTC [64] LOG:  checkpoint complete: wrote 44 buffers (0.3%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.007 s, sync=0.006 s, total=0.024 s; sync files=13, longest=0.004 s, average=0.001 s; distance=250 kB, estimate=250 kB; lsn=0/195FA00, redo lsn=0/195FA00
db-1     | 2024-02-13 23:51:45.618 UTC [1] LOG:  database system is shut down
db-1 exited with code 0
