time="2024-02-24T00:44:33Z" level=warning msg="The \"WATCH\" variable is not set. Defaulting to a blank string."
time="2024-02-24T00:44:33Z" level=warning msg="The \"WATCH\" variable is not set. Defaulting to a blank string."
 Network rinha-nginx-2024-q1  Creating
 Network rinha-nginx-2024-q1  Created
 Container crebitojs-db-1  Creating
 Container crebitojs-db-1  Created
 Container crebitojs-api02-1  Creating
 Container crebitojs-api01-1  Creating
 Container crebitojs-api02-1  Created
 Container crebitojs-api01-1  Created
 Container crebitojs-nginx-1  Creating
 Container crebitojs-nginx-1  Created
Attaching to api01-1, api02-1, db-1, nginx-1
db-1     | The files belonging to this database system will be owned by user "postgres".
db-1     | This user must also own the server process.
db-1     | 
db-1     | The database cluster will be initialized with locale "en_US.utf8".
db-1     | The default database encoding has accordingly been set to "UTF8".
db-1     | The default text search configuration will be set to "english".
db-1     | 
db-1     | Data page checksums are disabled.
db-1     | 
db-1     | fixing permissions on existing directory /var/lib/postgresql/data ... ok
db-1     | creating subdirectories ... ok
db-1     | selecting dynamic shared memory implementation ... posix
db-1     | selecting default max_connections ... 100
db-1     | selecting default shared_buffers ... 128MB
db-1     | selecting default time zone ... Etc/UTC
db-1     | creating configuration files ... ok
nginx-1  | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
nginx-1  | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
nginx-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
nginx-1  | 10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
nginx-1  | 10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
nginx-1  | /docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh
nginx-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
nginx-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
db-1     | running bootstrap script ... ok
nginx-1  | /docker-entrypoint.sh: Configuration complete; ready for start up
api01-1  | 
api01-1  | > rinha-de-backend-2024-q1-lucashmsilva@1.0.0 start
api01-1  | > node ./src/app.js
api01-1  | 
api02-1  | 
api02-1  | > rinha-de-backend-2024-q1-lucashmsilva@1.0.0 start
api02-1  | > node ./src/app.js
api02-1  | 
api01-1  | Server started on port 3000
api02-1  | Server started on port 3000
db-1     | performing post-bootstrap initialization ... ok
db-1     | initdb: warning: enabling "trust" authentication for local connections
db-1     | initdb: hint: You can change this by editing pg_hba.conf or using the option -A, or --auth-local and --auth-host, the next time you run initdb.
db-1     | syncing data to disk ... ok
db-1     | 
db-1     | 
db-1     | Success. You can now start the database server using:
db-1     | 
db-1     |     pg_ctl -D /var/lib/postgresql/data -l logfile start
db-1     | 
db-1     | waiting for server to start....2024-02-24 00:44:37.931 UTC [48] LOG:  starting PostgreSQL 16.2 (Debian 16.2-1.pgdg120+2) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
db-1     | 2024-02-24 00:44:37.935 UTC [48] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db-1     | 2024-02-24 00:44:37.943 UTC [51] LOG:  database system was shut down at 2024-02-24 00:44:37 UTC
db-1     | 2024-02-24 00:44:37.950 UTC [48] LOG:  database system is ready to accept connections
db-1     |  done
db-1     | server started
db-1     | CREATE DATABASE
db-1     | 
db-1     | 
db-1     | /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/init.sql
db-1     | CREATE TABLE
db-1     | CREATE TABLE
db-1     | CREATE INDEX
db-1     | DO
db-1     | 
db-1     | 
db-1     | waiting for server to shut down...2024-02-24 00:44:38.438 UTC [48] LOG:  received fast shutdown request
db-1     | .2024-02-24 00:44:38.441 UTC [48] LOG:  aborting any active transactions
db-1     | 2024-02-24 00:44:38.515 UTC [48] LOG:  background worker "logical replication launcher" (PID 54) exited with exit code 1
db-1     | 2024-02-24 00:44:38.516 UTC [49] LOG:  shutting down
db-1     | 2024-02-24 00:44:38.519 UTC [49] LOG:  checkpoint starting: shutdown immediate
api01-1  | node:internal/process/promises:289
api01-1  |             triggerUncaughtException(err, true /* fromPromise */);
api01-1  |             ^
api01-1  | 
api01-1  | Error: connect ECONNREFUSED 192.168.32.2:5432
api01-1  |     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1595:16)
api01-1  |     at cachedError (/api/node_modules/postgres/cjs/src/query.js:170:23)
api01-1  |     at new Query (/api/node_modules/postgres/cjs/src/query.js:36:24)
api01-1  |     at sql (/api/node_modules/postgres/cjs/src/index.js:112:11)
api01-1  |     at Object.run (/api/src/extrato-get.js:13:29) {
api01-1  |   errno: -111,
api01-1  |   code: 'ECONNREFUSED',
api01-1  |   syscall: 'connect',
api01-1  |   address: '192.168.32.2',
api01-1  |   port: 5432
api01-1  | }
api01-1  | 
api01-1  | Node.js v20.11.1
nginx-1  | 2024/02/24 00:44:38 [error] 29#29: *1 upstream prematurely closed connection while reading response header from upstream, client: 192.168.32.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.32.3:3000/clientes/1/extrato", host: "localhost:9999"
api01-1  | npm notice 
api01-1  | npm notice New minor version of npm available! 10.2.4 -> 10.4.0
api01-1  | npm notice Changelog: <https://github.com/npm/cli/releases/tag/v10.4.0>
api01-1  | npm notice Run `npm install -g npm@10.4.0` to update!
api01-1  | npm notice 
api02-1  | node:internal/process/promises:289
api02-1  |             triggerUncaughtException(err, true /* fromPromise */);
api02-1  |             ^
api02-1  | 
api02-1  | Error: connect ECONNREFUSED 192.168.32.2:5432
api02-1  |     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1595:16)
api02-1  |     at cachedError (/api/node_modules/postgres/cjs/src/query.js:170:23)
api02-1  |     at new Query (/api/node_modules/postgres/cjs/src/query.js:36:24)
api02-1  |     at sql (/api/node_modules/postgres/cjs/src/index.js:112:11)
api02-1  |     at Object.run (/api/src/extrato-get.js:13:29) {
api02-1  |   errno: -111,
api02-1  |   code: 'ECONNREFUSED',
api02-1  |   syscall: 'connect',
api02-1  |   address: '192.168.32.2',
api02-1  |   port: 5432
api02-1  | }
api02-1  | 
api02-1  | Node.js v20.11.1
nginx-1  | 2024/02/24 00:44:38 [error] 29#29: *1 upstream prematurely closed connection while reading response header from upstream, client: 192.168.32.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.32.4:3000/clientes/1/extrato", host: "localhost:9999"
api02-1  | npm notice 
api02-1  | npm notice New minor version of npm available! 10.2.4 -> 10.4.0
api02-1  | npm notice Changelog: <https://github.com/npm/cli/releases/tag/v10.4.0>
api02-1  | npm notice Run `npm install -g npm@10.4.0` to update!
api02-1  | npm notice 
db-1     | 2024-02-24 00:44:39.044 UTC [49] LOG:  checkpoint complete: wrote 937 buffers (5.7%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.219 s, sync=0.287 s, total=0.529 s; sync files=315, longest=0.209 s, average=0.001 s; distance=4292 kB, estimate=4292 kB; lsn=0/191BCD8, redo lsn=0/191BCD8
db-1     | 2024-02-24 00:44:39.050 UTC [48] LOG:  database system is shut down
db-1     |  done
db-1     | server stopped
db-1     | 
db-1     | PostgreSQL init process complete; ready for start up.
db-1     | 
db-1     | 2024-02-24 00:44:39.162 UTC [1] LOG:  starting PostgreSQL 16.2 (Debian 16.2-1.pgdg120+2) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
db-1     | 2024-02-24 00:44:39.183 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db-1     | 2024-02-24 00:44:39.183 UTC [1] LOG:  listening on IPv6 address "::", port 5432
db-1     | 2024-02-24 00:44:39.954 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
api02-1 exited with code 1
db-1     | 2024-02-24 00:44:39.978 UTC [66] LOG:  database system was shut down at 2024-02-24 00:44:39 UTC
db-1     | 2024-02-24 00:44:40.147 UTC [1] LOG:  database system is ready to accept connections
api01-1 exited with code 1
nginx-1  | 2024/02/24 00:44:40 [error] 29#29: *4 no live upstreams while connecting to upstream, client: 192.168.32.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/24 00:44:42 [error] 29#29: *5 no live upstreams while connecting to upstream, client: 192.168.32.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/24 00:44:44 [error] 29#29: *6 no live upstreams while connecting to upstream, client: 192.168.32.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/24 00:44:46 [error] 29#29: *7 no live upstreams while connecting to upstream, client: 192.168.32.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/24 00:44:48 [error] 29#29: *8 no live upstreams while connecting to upstream, client: 192.168.32.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/24 00:45:50 [error] 29#29: *9 upstream timed out (110: Connection timed out) while connecting to upstream, client: 192.168.32.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.32.4:3000/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/24 00:46:09 [error] 29#29: *9 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.32.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.32.3:3000/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/24 00:46:14 [error] 29#29: *12 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.32.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.32.4:3000/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/24 00:46:14 [error] 29#29: *12 no live upstreams while connecting to upstream, client: 192.168.32.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/24 00:46:16 [error] 29#29: *14 no live upstreams while connecting to upstream, client: 192.168.32.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/24 00:46:18 [error] 29#29: *15 no live upstreams while connecting to upstream, client: 192.168.32.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/24 00:46:23 [error] 29#29: *16 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.32.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.32.3:3000/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/24 00:46:23 [error] 29#29: *16 no live upstreams while connecting to upstream, client: 192.168.32.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/24 00:46:28 [error] 29#29: *18 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.32.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.32.4:3000/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/24 00:46:28 [error] 29#29: *18 no live upstreams while connecting to upstream, client: 192.168.32.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/24 00:46:30 [error] 29#29: *20 no live upstreams while connecting to upstream, client: 192.168.32.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/24 00:46:32 [error] 29#29: *21 no live upstreams while connecting to upstream, client: 192.168.32.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/24 00:46:37 [error] 29#29: *22 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.32.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.32.3:3000/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/24 00:46:37 [error] 29#29: *22 no live upstreams while connecting to upstream, client: 192.168.32.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/24 00:46:42 [error] 29#29: *24 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.32.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.32.4:3000/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/24 00:46:42 [error] 29#29: *24 no live upstreams while connecting to upstream, client: 192.168.32.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/24 00:46:44 [error] 29#29: *26 no live upstreams while connecting to upstream, client: 192.168.32.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/24 00:46:46 [error] 29#29: *27 no live upstreams while connecting to upstream, client: 192.168.32.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/24 00:46:51 [error] 29#29: *28 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.32.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.32.3:3000/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/24 00:46:51 [error] 29#29: *28 no live upstreams while connecting to upstream, client: 192.168.32.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/24 00:46:56 [error] 29#29: *30 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.32.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.32.4:3000/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/24 00:46:56 [error] 29#29: *30 no live upstreams while connecting to upstream, client: 192.168.32.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1 exited with code 0
nginx-1 exited with code 0
db-1     | 2024-02-24 00:46:59.585 UTC [1] LOG:  received fast shutdown request
db-1     | 2024-02-24 00:46:59.588 UTC [1] LOG:  aborting any active transactions
db-1     | 2024-02-24 00:46:59.591 UTC [1] LOG:  background worker "logical replication launcher" (PID 69) exited with exit code 1
db-1     | 2024-02-24 00:46:59.591 UTC [64] LOG:  shutting down
db-1     | 2024-02-24 00:46:59.600 UTC [64] LOG:  checkpoint starting: shutdown immediate
db-1     | 2024-02-24 00:46:59.648 UTC [64] LOG:  checkpoint complete: wrote 25 buffers (0.2%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.007 s, sync=0.017 s, total=0.057 s; sync files=13, longest=0.004 s, average=0.002 s; distance=16 kB, estimate=16 kB; lsn=0/191FE00, redo lsn=0/191FE00
db-1     | 2024-02-24 00:46:59.651 UTC [1] LOG:  database system is shut down
db-1 exited with code 0
