 Network elioenaiferrari-rust_rinha2024  Creating
 Network elioenaiferrari-rust_rinha2024  Created
 Container elioenaiferrari-rust-postgres-1  Creating
 Container elioenaiferrari-rust-postgres-1  Created
 Container elioenaiferrari-rust-instance_1-1  Creating
 Container elioenaiferrari-rust-instance_1-1  Created
 Container elioenaiferrari-rust-instance_2-1  Creating
 Container elioenaiferrari-rust-instance_2-1  Created
 Container elioenaiferrari-rust-nginx-1  Creating
 Container elioenaiferrari-rust-nginx-1  Created
Attaching to instance_1-1, instance_2-1, nginx-1, postgres-1
postgres-1    | The files belonging to this database system will be owned by user "postgres".
postgres-1    | This user must also own the server process.
postgres-1    | 
postgres-1    | The database cluster will be initialized with locale "en_US.utf8".
postgres-1    | The default database encoding has accordingly been set to "UTF8".
postgres-1    | The default text search configuration will be set to "english".
postgres-1    | 
postgres-1    | Data page checksums are disabled.
postgres-1    | 
postgres-1    | fixing permissions on existing directory /var/lib/postgresql/data ... ok
postgres-1    | creating subdirectories ... ok
postgres-1    | selecting dynamic shared memory implementation ... posix
postgres-1    | selecting default max_connections ... 100
postgres-1    | selecting default shared_buffers ... 128MB
postgres-1    | selecting default time zone ... UTC
postgres-1    | creating configuration files ... ok
postgres-1    | running bootstrap script ... ok
postgres-1    | sh: locale: not found
postgres-1    | 2024-02-18 01:48:59.514 UTC [30] WARNING:  no usable system locales were found
postgres-1    | performing post-bootstrap initialization ... ok
postgres-1    | syncing data to disk ... ok
postgres-1    | 
postgres-1    | 
postgres-1    | Success. You can now start the database server using:
postgres-1    | 
postgres-1    |     pg_ctl -D /var/lib/postgresql/data -l logfile start
postgres-1    | 
postgres-1    | initdb: warning: enabling "trust" authentication for local connections
postgres-1    | initdb: hint: You can change this by editing pg_hba.conf or using the option -A, or --auth-local and --auth-host, the next time you run initdb.
postgres-1    | waiting for server to start....2024-02-18 01:49:01.190 UTC [36] LOG:  starting PostgreSQL 16.2 on x86_64-pc-linux-musl, compiled by gcc (Alpine 13.2.1_git20231014) 13.2.1 20231014, 64-bit
postgres-1    | 2024-02-18 01:49:01.193 UTC [36] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgres-1    | 2024-02-18 01:49:01.203 UTC [39] LOG:  database system was shut down at 2024-02-18 01:49:00 UTC
postgres-1    | 2024-02-18 01:49:01.209 UTC [36] LOG:  database system is ready to accept connections
postgres-1    |  done
postgres-1    | server started
postgres-1    | CREATE DATABASE
postgres-1    | 
postgres-1    | 
postgres-1    | /usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*
postgres-1    | 
postgres-1    | waiting for server to shut down....2024-02-18 01:49:01.347 UTC [36] LOG:  received fast shutdown request
postgres-1    | 2024-02-18 01:49:01.350 UTC [36] LOG:  aborting any active transactions
postgres-1    | 2024-02-18 01:49:01.352 UTC [36] LOG:  background worker "logical replication launcher" (PID 42) exited with exit code 1
postgres-1    | 2024-02-18 01:49:01.354 UTC [37] LOG:  shutting down
postgres-1    | 2024-02-18 01:49:01.357 UTC [37] LOG:  checkpoint starting: shutdown immediate
postgres-1    | 2024-02-18 01:49:01.846 UTC [37] LOG:  checkpoint complete: wrote 925 buffers (5.6%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.413 s, sync=0.065 s, total=0.493 s; sync files=301, longest=0.034 s, average=0.001 s; distance=4269 kB, estimate=4269 kB; lsn=0/191BA38, redo lsn=0/191BA38
postgres-1    | 2024-02-18 01:49:01.852 UTC [36] LOG:  database system is shut down
postgres-1    |  done
postgres-1    | server stopped
postgres-1    | 
postgres-1    | PostgreSQL init process complete; ready for start up.
postgres-1    | 
postgres-1    | 2024-02-18 01:49:01.970 UTC [1] LOG:  starting PostgreSQL 16.2 on x86_64-pc-linux-musl, compiled by gcc (Alpine 13.2.1_git20231014) 13.2.1 20231014, 64-bit
postgres-1    | 2024-02-18 01:49:01.970 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
postgres-1    | 2024-02-18 01:49:01.970 UTC [1] LOG:  listening on IPv6 address "::", port 5432
postgres-1    | 2024-02-18 01:49:01.975 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgres-1    | 2024-02-18 01:49:01.981 UTC [52] LOG:  database system was shut down at 2024-02-18 01:49:01 UTC
postgres-1    | 2024-02-18 01:49:01.989 UTC [1] LOG:  database system is ready to accept connections
instance_1-1  | Applied 20240215194128/migrate create tables (21.940412ms)
nginx-1       | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
nginx-1       | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
nginx-1       | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
nginx-1       | 10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
nginx-1       | 10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
nginx-1       | /docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh
nginx-1       | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
nginx-1       | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
nginx-1       | /docker-entrypoint.sh: Configuration complete; ready for start up
nginx-1       | 2024/02/18 01:49:06 [error] 30#30: *3 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.112.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.112.4:4001/clientes/1/extrato", host: "localhost:9999"
nginx-1       | 2024/02/18 01:49:17 [error] 30#30: *166 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.112.1, server: , request: "POST /clientes/1/transacoes HTTP/1.1", upstream: "http://192.168.112.4:4001/clientes/1/transacoes", host: "localhost:9999"
nginx-1       | 2024/02/18 01:49:28 [error] 30#30: *563 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.112.1, server: , request: "POST /clientes/4/transacoes HTTP/1.1", upstream: "http://192.168.112.4:4001/clientes/4/transacoes", host: "localhost:9999"
nginx-1       | 2024/02/18 01:49:39 [error] 30#30: *1644 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.112.1, server: , request: "POST /clientes/4/transacoes HTTP/1.1", upstream: "http://192.168.112.4:4001/clientes/4/transacoes", host: "localhost:9999"
nginx-1       | 2024/02/18 01:49:50 [error] 30#30: *3401 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.112.1, server: , request: "POST /clientes/4/transacoes HTTP/1.1", upstream: "http://192.168.112.4:4001/clientes/4/transacoes", host: "localhost:9999"
nginx-1       | 2024/02/18 01:50:01 [error] 30#30: *5840 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.112.1, server: , request: "POST /clientes/1/transacoes HTTP/1.1", upstream: "http://192.168.112.4:4001/clientes/1/transacoes", host: "localhost:9999"
nginx-1       | 2024/02/18 01:50:12 [error] 30#30: *8957 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.112.1, server: , request: "POST /clientes/2/transacoes HTTP/1.1", upstream: "http://192.168.112.4:4001/clientes/2/transacoes", host: "localhost:9999"
nginx-1       | 2024/02/18 01:50:23 [error] 30#30: *12756 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.112.1, server: , request: "POST /clientes/1/transacoes HTTP/1.1", upstream: "http://192.168.112.4:4001/clientes/1/transacoes", host: "localhost:9999"
nginx-1       | 2024/02/18 01:50:34 [error] 30#30: *17233 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.112.1, server: , request: "POST /clientes/5/transacoes HTTP/1.1", upstream: "http://192.168.112.4:4001/clientes/5/transacoes", host: "localhost:9999"
nginx-1       | 2024/02/18 01:50:45 [error] 30#30: *22390 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.112.1, server: , request: "POST /clientes/5/transacoes HTTP/1.1", upstream: "http://192.168.112.4:4001/clientes/5/transacoes", host: "localhost:9999"
nginx-1       | 2024/02/18 01:50:56 [error] 30#30: *28225 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.112.1, server: , request: "POST /clientes/4/transacoes HTTP/1.1", upstream: "http://192.168.112.4:4001/clientes/4/transacoes", host: "localhost:9999"
nginx-1       | 2024/02/18 01:51:07 [error] 30#30: *34740 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.112.1, server: , request: "POST /clientes/3/transacoes HTTP/1.1", upstream: "http://192.168.112.4:4001/clientes/3/transacoes", host: "localhost:9999"
nginx-1       | 2024/02/18 01:51:18 [error] 30#30: *41935 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.112.1, server: , request: "POST /clientes/3/transacoes HTTP/1.1", upstream: "http://192.168.112.4:4001/clientes/3/transacoes", host: "localhost:9999"
nginx-1       | 2024/02/18 01:51:29 [error] 30#30: *49416 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.112.1, server: , request: "POST /clientes/5/transacoes HTTP/1.1", upstream: "http://192.168.112.4:4001/clientes/5/transacoes", host: "localhost:9999"
nginx-1       | 2024/02/18 01:51:40 [error] 30#30: *56897 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.112.1, server: , request: "POST /clientes/3/transacoes HTTP/1.1", upstream: "http://192.168.112.4:4001/clientes/3/transacoes", host: "localhost:9999"
nginx-1       | 2024/02/18 01:51:51 [error] 30#30: *64378 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.112.1, server: , request: "POST /clientes/5/transacoes HTTP/1.1", upstream: "http://192.168.112.4:4001/clientes/5/transacoes", host: "localhost:9999"
nginx-1       | 2024/02/18 01:52:02 [error] 30#30: *71859 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.112.1, server: , request: "POST /clientes/3/transacoes HTTP/1.1", upstream: "http://192.168.112.4:4001/clientes/3/transacoes", host: "localhost:9999"
nginx-1       | 2024/02/18 01:52:13 [error] 30#30: *79340 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.112.1, server: , request: "POST /clientes/1/transacoes HTTP/1.1", upstream: "http://192.168.112.4:4001/clientes/1/transacoes", host: "localhost:9999"
nginx-1       | 2024/02/18 01:52:24 [error] 30#30: *86819 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.112.1, server: , request: "POST /clientes/3/transacoes HTTP/1.1", upstream: "http://192.168.112.4:4001/clientes/3/transacoes", host: "localhost:9999"
nginx-1       | 2024/02/18 01:52:35 [error] 30#30: *94302 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.112.1, server: , request: "POST /clientes/1/transacoes HTTP/1.1", upstream: "http://192.168.112.4:4001/clientes/1/transacoes", host: "localhost:9999"
nginx-1       | 2024/02/18 01:52:46 [error] 30#30: *101783 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.112.1, server: , request: "POST /clientes/4/transacoes HTTP/1.1", upstream: "http://192.168.112.4:4001/clientes/4/transacoes", host: "localhost:9999"
nginx-1       | 2024/02/18 01:52:57 [error] 30#30: *109262 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.112.1, server: , request: "POST /clientes/5/transacoes HTTP/1.1", upstream: "http://192.168.112.4:4001/clientes/5/transacoes", host: "localhost:9999"
nginx-1       | 2024/02/18 01:53:08 [error] 30#30: *116745 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.112.1, server: , request: "POST /clientes/4/transacoes HTTP/1.1", upstream: "http://192.168.112.4:4001/clientes/4/transacoes", host: "localhost:9999"
nginx-1 exited with code 0
nginx-1 exited with code 0
instance_2-1 exited with code 0
instance_2-1 exited with code 137
instance_1-1 exited with code 0
instance_1-1 exited with code 137
postgres-1    | 2024-02-18 01:53:41.243 UTC [1] LOG:  received fast shutdown request
postgres-1    | 2024-02-18 01:53:41.249 UTC [1] LOG:  aborting any active transactions
postgres-1    | 2024-02-18 01:53:41.252 UTC [1] LOG:  background worker "logical replication launcher" (PID 55) exited with exit code 1
postgres-1    | 2024-02-18 01:53:41.252 UTC [50] LOG:  shutting down
postgres-1    | 2024-02-18 01:53:41.255 UTC [50] LOG:  checkpoint starting: shutdown immediate
postgres-1    | 2024-02-18 01:53:41.480 UTC [50] LOG:  checkpoint complete: wrote 492 buffers (3.0%); 0 WAL file(s) added, 0 removed, 1 recycled; write=0.012 s, sync=0.195 s, total=0.229 s; sync files=73, longest=0.150 s, average=0.003 s; distance=11402 kB, estimate=11402 kB; lsn=0/243E600, redo lsn=0/243E600
postgres-1    | 2024-02-18 01:53:41.484 UTC [1] LOG:  database system is shut down
postgres-1 exited with code 0
